name: ArenaProtector
version: '${version}'
author: GreenedDev
main: net.multylands.plugins.ArenaProtector
api-version: '1.20'
softdepend:
  - Multiverse-Core
commands:
  arenaprotector:
    description: "the main command of arenaprotector"
